[package]
name = "axum-tools"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
axum-model.workspace = true
ignore.workspace = true
serde.workspace = true
similar.workspace = true
serde_json.workspace = true


[lints]
workspace = true
