[package]
name = "axon-cli"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[[bin]]
name = "axon"
path = "src/main.rs"

[dependencies]
rustix.workspace = true
base64.workspace = true
reqwest.workspace = true
axon-model.workspace = true
anyhow.workspace = true
axon-ipc.workspace = true
axon-proto.workspace = true
axon-host.workspace = true
axon-lua.workspace = true
axon-provider.workspace = true
axon-tools.workspace = true
axon-testkit.workspace = true
axon-agent.workspace = true
axon-tui.workspace = true
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
axon-journal.workspace = true
serde_json.workspace = true

[lints]
workspace = true
