-- axum's configuration.
--
-- A program, not a data file: it can probe the machine it runs on, loop over a directory of
-- endpoints, and branch on what answers. Settings are assigned, descriptions are handed to a
-- registrar, and the file returns nothing.
--
-- Everything beside this file is loaded before it, so you can override any of it here:
--
--   apis/*.lua      the wire protocols — how to talk to an endpoint
--   providers.lua   the catalog — which endpoints exist and what they offer
--
-- Edit those directly, or leave them alone and add what you need here. `make configs` copies
-- this directory over the top again, so keep your own additions in a file of your own if you
-- expect to re-run it.

-- Which model to use, as `axum models` prints it.
axum.model = "anthropic/claude-sonnet-4-5"

-- An endpoint of your own needs no protocol of its own if it speaks a dialect axum knows:
--
-- axum.provider("my-box", {
--   name = "My GPU box",
--   api = "openai-completions",
--   base_url = "http://10.0.0.7:8000/v1",
--   auth = { kind = "none" },
--   models = {
--     { id = "qwen3-coder", name = "Qwen3 Coder", context_window = 262144, max_tokens = 32768 },
--   },
-- })
--
-- Registration is keyed, so declaring the same id twice replaces rather than appends — which
-- is what makes a loop over a directory of machines safe to re-run.

-- Whether `read`, `write` and `edit` refuse paths outside the session's directory.
--
-- Off. It was on, and the effect was a detour rather than safety: asked to edit a file in
-- /tmp, the model was told the path was outside the session and reached for the shell instead,
-- doing the same edit through a heredoc — no diff, no review, and through the one tool that
-- has no confinement at all. A rule only the careful tools obey moves work to the careless one.
--
-- Turn it on if you want the wall, but the thing that actually contains anything is running
-- the shell peer under `bwrap`: see `tools/bash-sandboxed.lua` in the examples.
--
-- axum.confine = true

-- Permissions granted in advance, so they are not asked about.
--
-- A tool that is about to read a file, write one, or run a command stops and asks — unless one
-- of these already covers it. That is on by default and not a mode you opt into: sandboxing
-- that has to be switched on is off for everybody who has not already thought about it, which
-- is everybody it was meant to protect.
--
-- Each rule is a verb (`read`, `write`, `run`, `reach`) and one width:
--
--   anything = true        every action of that verb, anywhere
--   directory = "/path"    that path and everything under it
--   program = "git"        any command whose first word is this
--
-- A rule naming no width grants nothing, rather than being read as `anything`.
--
-- axum.allow = {
--   { verb = "read",  directory = "/home/you/work" },
--   { verb = "run",   program = "git" },
-- }
