-- axon's configuration, and its only entry point.
--
-- A program, not a data file: it may probe the machine, loop, and branch. Settings are
-- assigned, descriptions go to a registrar, and the file returns nothing.

-- What runs. Nothing is discovered by scanning: a file not named here does not load.
-- Clients first — a tool loads its sibling's client library as it declares itself.
axon.load("clients/hexe.lua")
axon.load("clients/oslo.lua")
axon.load("apis.lua")
axon.load("providers.lua")
axon.load("tools.lua")

-- Which model to use, as `axon models` prints it.
axon.model = "anthropic/claude-sonnet-4-5"

-- An endpoint of your own, if it speaks a dialect axon already knows. Registration is keyed,
-- so declaring the same id twice replaces rather than appends.
--
-- axon.provider("my-box", {
--   name = "My GPU box",
--   api = "openai-completions",
--   base_url = "http://10.0.0.7:8000/v1",
--   auth = { kind = "none" },
--   models = {
--     { id = "qwen3-coder", name = "Qwen3 Coder", context_window = 262144, max_tokens = 32768 },
--   },
-- })

-- Whether `read`, `write` and `edit` refuse paths outside the session's directory. Off: it
-- moved work to the shell, which has no confinement at all. `bwrap` in front of the shell peer
-- is what actually contains anything.
--
-- axon.confine = true

-- Permissions granted in advance, so they are not asked about. Each rule is a verb — `read`,
-- `write`, `run`, `reach` — and one width. A rule naming no width grants nothing.
--
--   anything = true        every action of that verb, anywhere
--   directory = "/path"    that path and everything under it
--   program = "git"        any command whose first word is this
--
-- axon.allow = {
--   { verb = "read",  directory = "/home/you/work" },
--   { verb = "run",   program = "git" },
-- }

-- How long a daemon stays up with nobody attached and nothing running, in seconds. Detaching
-- is not ending a session, so this is a grace period rather than a hangup; 0 keeps it forever.
--
-- axon.idle_exit = 600

-- Environment every process axon starts is given, on top of what it inherits. `OSLO_PROFILE`
-- is set to "axon" whether or not this says so, and naming it here overrides that.
--
-- axon.env = { PAGER = "cat", RUST_LOG = "warn" }

-- Directories whose `.axon.lua` is as trusted as this file. A project file may otherwise set
-- settings but not declare a provider, a tool or a peer.
--
-- axon.trusted = { "/home/you/work" }

-- ---------------------------------------------------------------------- the screen
--
-- Everything the UI draws with is a setting under `axon.ui`. Three kinds:
--
-- COLOURS are palette indices, 0-255, and mean whatever your terminal says they mean:
--
--   accent  success  warning  error  typed
--   md_heading  md_code  md_code_block  md_quote
--   diff_added  diff_added_bg  diff_removed  diff_removed_bg  diff_context
--   tool_bg  tool_title  tool_ok  tool_failed  tool_output  tool_fold
--   menu_selected_bg  menu_selected  menu_detail  menu_detail_selected  menu_meta
--   border  scan  hint  rule
--   message_rail  message_bg  message_text
--   thinking  text  muted  dim
--
-- `border` and `scan` are the ends of a gradient: the light walks the indices between them, so
-- keep them far enough apart to have something to walk.
--
-- GLYPHS are any string, and width is your problem — a two-column glyph draws two columns:
--
--   corner_top_left  corner_top_right  corner_bottom_left  corner_bottom_right
--   edge_horizontal  edge_vertical
--   marker  no_marker  ellipsis  bullet
--   more_rule  expand  collapse  quote_rule  notice_rule
--   placeholder  placeholder_short  no_model  decrypt_pool
--   spinner            a list of frames: { "◐", "◓", "◑", "◒" }
--
-- NUMBERS are rows, budgets and rates. Anything named `_share` is a percentage. A value under
-- its floor is raised rather than refused:
--
--   footer_rows  status_rows  prompt_min_rows
--   live_rows  live_share  prompt_share  prompt_min_lines
--   menu_rows  preview_lines  page_share
--   block_pad  gutter  tab_width  column_gap  min_column
--   summary_budget  argument_floor
--   frame_ms  scan_speed  scan_nose  scan_tail
--   rest_pace  hold_pace  work_pace  decrypt_ms

-- The opening scramble: text lands as noise and resolves into itself over `decrypt_ms`
-- milliseconds. Zero, the built-in, is no effect -- set it to switch the thing on. It runs once,
-- over the whole screen, and leaves the box and every other frame character alone.
--
-- axon.ui.decrypt_ms = 900
-- axon.ui.decrypt_pool = "01"

-- For a palette generated by lule, where 1-6 are pigments in chroma order rather than hues and
-- 232-255 runs black → colour 0 → accent → colour 15 → white:
--
-- axon.ui = {
--   accent = 1, success = 2, warning = 3, error = 9,
--   md_heading = 5, md_code = 1, md_code_block = 2, md_quote = 250,
--   diff_added = 2, diff_removed = 9, diff_context = 250,
--   typed = 14,
--   dim = 8, muted = 250, text = 252, thinking = 250, rule = 8, hint = 8,
--   tool_title = 254, tool_ok = 2, tool_failed = 9, tool_output = 251, tool_fold = 8,
--   menu_selected = 255, menu_detail = 250, menu_detail_selected = 255, menu_meta = 8,
--   message_text = 254,
--   -- 232-236 is below your background: a surface there is a hole.
--   tool_bg = 239, menu_selected_bg = 242, message_bg = 242,
--   -- Keep the border low: 243-244 is your accent at full strength, and a border there glows
--   -- brightly enough that the light moving along it disappears into its own frame.
--   border = 238, scan = 254,
-- }

-- What axon tells the model it is. axon appends the session's facts (directory, platform,
-- date) and the project's `AGENTS.md`.
axon.system = [[
You are axon, a coding agent working in a terminal alongside a person at their computer.

Do the work rather than describing it. When a change is needed, make it with `edit` or `write`;
when something needs checking, check it with `read` or `shell`. Prefer reading the code to
guessing about it, and prefer running a command to predicting its output.

Match the code you are editing: its naming, its idioms, its comment density. A change that
reads like the file around it is easier to review than one that is merely correct.

Be brief. The person is reading a terminal, not a report. Say what you did and what it means;
skip preamble, skip summarising what they just watched happen, and do not close by offering
further help. If something failed, say so plainly with the output rather than hedging.

Ask only when the answer would change what you do and you cannot find it yourself. Otherwise
make the ordinary judgement call, say which one you made, and carry on.
]]
