-- axum's configuration.
--
-- A program, not a data file: it can probe the machine it runs on, loop over a directory of
-- endpoints, and branch on what answers. Settings are assigned, descriptions are handed to a
-- registrar, and the file returns nothing.
--
-- Everything beside this file is loaded before it, so you can override any of it here:
--
--   apis/*.lua      the wire protocols — how to talk to an endpoint
--   providers.lua   the catalog — which endpoints exist and what they offer
--
-- Edit those directly, or leave them alone and add what you need here. `make configs` copies
-- this directory over the top again, so keep your own additions in a file of your own if you
-- expect to re-run it.

-- Which model to use, as `axum models` prints it.
axum.model = "anthropic/claude-sonnet-4-5"

-- An endpoint of your own needs no protocol of its own if it speaks a dialect axum knows:
--
-- axum.provider("my-box", {
--   name = "My GPU box",
--   api = "openai-completions",
--   base_url = "http://10.0.0.7:8000/v1",
--   auth = { kind = "none" },
--   models = {
--     { id = "qwen3-coder", name = "Qwen3 Coder", context_window = 262144, max_tokens = 32768 },
--   },
-- })
--
-- Registration is keyed, so declaring the same id twice replaces rather than appends — which
-- is what makes a loop over a directory of machines safe to re-run.

-- Whether `read`, `write` and `edit` refuse paths outside the session's directory.
--
-- Off. It was on, and the effect was a detour rather than safety: asked to edit a file in
-- /tmp, the model was told the path was outside the session and reached for the shell instead,
-- doing the same edit through a heredoc — no diff, no review, and through the one tool that
-- has no confinement at all. A rule only the careful tools obey moves work to the careless one.
--
-- Turn it on if you want the wall, but the thing that actually contains anything is running
-- the shell peer under `bwrap`: see `tools/bash-sandboxed.lua` in the examples.
--
-- axum.confine = true

-- Permissions granted in advance, so they are not asked about.
--
-- A tool that is about to read a file, write one, or run a command stops and asks — unless one
-- of these already covers it. That is on by default and not a mode you opt into: sandboxing
-- that has to be switched on is off for everybody who has not already thought about it, which
-- is everybody it was meant to protect.
--
-- Each rule is a verb (`read`, `write`, `run`, `reach`) and one width:
--
--   anything = true        every action of that verb, anywhere
--   directory = "/path"    that path and everything under it
--   program = "git"        any command whose first word is this
--
-- A rule naming no width grants nothing, rather than being read as `anything`.
--
-- axum.allow = {
--   { verb = "read",  directory = "/home/you/work" },
--   { verb = "run",   program = "git" },
-- }

-- ---------------------------------------------------------------------- the screen
--
-- `axum.ui` is every visual decision the UI makes: what colour a thing is, what character it is
-- drawn with, how big it is, and how fast it moves. One flat table, and every name is optional —
-- what you do not mention keeps its built-in value.
--
--   axum.ui.accent    = 1        -- a colour: an index into your terminal's palette
--   axum.ui.marker    = "▶ "     -- a glyph: whatever string you want drawn there
--   axum.ui.menu_rows = 12       -- a number
--
-- Nothing here is a hex value. A person who has set their terminal's colours has already said
-- what things should look like, and a program that answers again over the top is the one window
-- on the screen that does not match the others. The defaults are the ordinary xterm reading —
-- 1 red, 2 green, 3 yellow, 6 cyan, 232-255 the 24-step greyscale — because that is what a
-- terminal nobody has configured actually holds.

-- COLOURS. Roles that share a default are still separate names: `tool_output` and `md_quote`
-- happen to be the same grey and are not the same decision.
--
--   accent               spinners, list cursors, markdown bullets
--   success  warning  error
--   typed                the characters you have typed, inside a completion
--   md_heading  md_code  md_code_block  md_quote
--   diff_added  diff_removed  diff_context
--   tool_bg  tool_title  tool_ok  tool_failed  tool_output  tool_fold
--   menu_bg  menu_selected_bg  menu_selected
--   menu_detail  menu_detail_selected  menu_meta
--   border               the prompt's box with nothing lit
--   scan                 the brightest point of the light travelling along it
--   hint                 the prompt's own text, before you type
--   rule                 the rule down the side of a quotation
--   message_bg  message_text        something you said
--   thinking  text  muted  dim
--
-- `border` and `scan` are the two ends of a gradient: the light walks the indices between them,
-- so put them far enough apart to have something to walk.

-- GLYPHS. Any string. Width is your problem — a two-column glyph draws two columns, and a box
-- corner that does will not line up.
--
--   corner_top_left  corner_top_right  corner_bottom_left  corner_bottom_right
--   edge_horizontal  edge_vertical
--   marker  no_marker           in front of a list row, chosen and not
--   ellipsis  bullet
--   quote_rule  notice_rule
--   placeholder  placeholder_short   what the prompt says before you type
--   no_model            what the footer says when nothing is configured to answer
--   spinner             a list of frames: { "◐", "◓", "◑", "◒" }

-- NUMBERS. Rows, budgets, percentages and rates. Anything named `_share` is a percentage,
-- because Lua has one number type and `0.3` and `30` should not mean different things by
-- accident.
--
--   footer_rows  status_rows  prompt_min_rows
--   live_rows  live_share          the transcript region
--   prompt_share  prompt_min_lines
--   menu_rows  preview_lines  page_share
--   block_pad  gutter  tab_width  column_gap  min_column
--   summary_budget  argument_floor      a tool call's arguments in a block header
--   frame_ms            milliseconds between frames
--   scan_speed          the border's light, as a percentage: 200 is twice as fast, 0 is still
--   scan_nose  scan_tail        cells lit ahead of the light and behind it
--   rest_pace  hold_pace  work_pace    cells per frame in each state, as a percentage
--
-- A value under a floor is raised rather than refused: zero rows of menu is not a preference.

-- A palette generated by lule is a different machine, and the colour defaults are all wrong on
-- it. Its slots 1-6 are the six most chromatic pigments of a wallpaper in chroma order — no hue
-- meaning, and `accent` and `cursor` both alias slot 1 — and its 232-255 is not a greyscale but
-- `black -> colour 0 -> accent -> colour 15 -> white`, which makes the middle of that range the
-- accent rather than a grey and puts your background at 236. Uncomment for that:
--
-- axum.ui = {
--   accent = 1, success = 2, warning = 3, error = 9,
--   md_heading = 5, md_code = 1, md_code_block = 2, md_quote = 8,
--   diff_added = 2, diff_removed = 9, diff_context = 8,
--   typed = 14,
--   -- 7 and 8 are lule's two greys; for a dark theme 7 is the darker of them.
--   dim = 7, muted = 8, text = 15, thinking = 8, rule = 8, hint = 7,
--   tool_title = 15, tool_ok = 2, tool_failed = 9, tool_output = 8, tool_fold = 7,
--   menu_selected = 255, menu_detail = 8, menu_detail_selected = 15, menu_meta = 7,
--   message_text = 15,
--   -- Above 236, because 232-236 runs black to your background: below it is a hole.
--   tool_bg = 237, menu_bg = 237, menu_selected_bg = 239, message_bg = 239,
--   -- The one place the tinted middle is wanted: this gradient runs through your own accent.
--   border = 240, scan = 253,
-- }
